truncate table ICSC_Monthly_KIA_Capture_Current_Members
truncate table ICSC_Monthly_KIA_Capture_Current_Prim_Members
truncate table ICSC_Monthly_KIA_Capture_Suspended_Members
truncate table ICSC_Monthly_KIA_Capture_Rejoined_Members
truncate table ICSC_Monthly_KIA_Capture_Renewed_Members
truncate table ICSC_Monthly_KIA_Capture_New_Members

select * from ICSC_Monthly_KIA_Capture_Current_Members